//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarifDefteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIF
    {
        public string ID { get; set; }
        public string URL { get; set; }
        public string SITE_ADI { get; set; }
        public string YEMEK_ADI { get; set; }
        public string RESIM { get; set; }
        public string MALZEMELER { get; set; }
        public string HAZIRLANIS { get; set; }
        public string KATEGORI { get; set; }
    }
}
