//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarifDefteri.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YemekTarifiEntities : DbContext
    {
        public YemekTarifiEntities()
            : base("name=YemekTarifiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TARIF> TARIF { get; set; }
    
        public virtual ObjectResult<sp_getSearchResults_Result> sp_getSearchResults(string search_param, Nullable<int> search_type)
        {
            var search_paramParameter = search_param != null ?
                new ObjectParameter("search_param", search_param) :
                new ObjectParameter("search_param", typeof(string));
    
            var search_typeParameter = search_type.HasValue ?
                new ObjectParameter("search_type", search_type) :
                new ObjectParameter("search_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getSearchResults_Result>("sp_getSearchResults", search_paramParameter, search_typeParameter);
        }
    }
}
