#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="YEMEK_TARIFI")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTARIF(TARIF instance);
    partial void UpdateTARIF(TARIF instance);
    partial void DeleteTARIF(TARIF instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WebCrawler.Properties.Settings.Default.YEMEK_TARIFIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VISITED_URL> VISITED_URLs
		{
			get
			{
				return this.GetTable<VISITED_URL>();
			}
		}
		
		public System.Data.Linq.Table<TARIF> TARIFs
		{
			get
			{
				return this.GetTable<TARIF>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VISITED_URLS")]
	public partial class VISITED_URL
	{
		
		private string _ID;
		
		private string _URL;
		
		public VISITED_URL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(64)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(255)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TARIF")]
	public partial class TARIF : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _URL;
		
		private string _SITE_ADI;
		
		private string _YEMEK_ADI;
		
		private string _RESIM;
		
		private string _MALZEMELER;
		
		private string _HAZIRLANIS;
		
		private string _KATEGORI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnSITE_ADIChanging(string value);
    partial void OnSITE_ADIChanged();
    partial void OnYEMEK_ADIChanging(string value);
    partial void OnYEMEK_ADIChanged();
    partial void OnRESIMChanging(string value);
    partial void OnRESIMChanged();
    partial void OnMALZEMELERChanging(string value);
    partial void OnMALZEMELERChanged();
    partial void OnHAZIRLANISChanging(string value);
    partial void OnHAZIRLANISChanged();
    partial void OnKATEGORIChanging(string value);
    partial void OnKATEGORIChanged();
    #endregion
		
		public TARIF()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(64) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_ADI", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SITE_ADI
		{
			get
			{
				return this._SITE_ADI;
			}
			set
			{
				if ((this._SITE_ADI != value))
				{
					this.OnSITE_ADIChanging(value);
					this.SendPropertyChanging();
					this._SITE_ADI = value;
					this.SendPropertyChanged("SITE_ADI");
					this.OnSITE_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEMEK_ADI", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string YEMEK_ADI
		{
			get
			{
				return this._YEMEK_ADI;
			}
			set
			{
				if ((this._YEMEK_ADI != value))
				{
					this.OnYEMEK_ADIChanging(value);
					this.SendPropertyChanging();
					this._YEMEK_ADI = value;
					this.SendPropertyChanged("YEMEK_ADI");
					this.OnYEMEK_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIM", DbType="NVarChar(MAX)")]
		public string RESIM
		{
			get
			{
				return this._RESIM;
			}
			set
			{
				if ((this._RESIM != value))
				{
					this.OnRESIMChanging(value);
					this.SendPropertyChanging();
					this._RESIM = value;
					this.SendPropertyChanged("RESIM");
					this.OnRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALZEMELER", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MALZEMELER
		{
			get
			{
				return this._MALZEMELER;
			}
			set
			{
				if ((this._MALZEMELER != value))
				{
					this.OnMALZEMELERChanging(value);
					this.SendPropertyChanging();
					this._MALZEMELER = value;
					this.SendPropertyChanged("MALZEMELER");
					this.OnMALZEMELERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZIRLANIS", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HAZIRLANIS
		{
			get
			{
				return this._HAZIRLANIS;
			}
			set
			{
				if ((this._HAZIRLANIS != value))
				{
					this.OnHAZIRLANISChanging(value);
					this.SendPropertyChanging();
					this._HAZIRLANIS = value;
					this.SendPropertyChanged("HAZIRLANIS");
					this.OnHAZIRLANISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KATEGORI", DbType="NVarChar(255)")]
		public string KATEGORI
		{
			get
			{
				return this._KATEGORI;
			}
			set
			{
				if ((this._KATEGORI != value))
				{
					this.OnKATEGORIChanging(value);
					this.SendPropertyChanging();
					this._KATEGORI = value;
					this.SendPropertyChanged("KATEGORI");
					this.OnKATEGORIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
